replaced etc/init.d/disbatchd with Daemon::Control sh script which calls etc/disbatch/disbatchd-init

diff --git a/etc/init.d/disbatchd b/etc/init.d/disbatchd
--- a/etc/init.d/disbatchd
+++ b/etc/init.d/disbatchd
@@ -6,83 +6,26 @@
 # description: Starts and stops the MongDB daemon that handles all \
 #              database requests.
 
-# Source function library.
-. /etc/rc.d/init.d/functions
+# Generated at Fri Jul 18 09:56:06 2014 with Daemon::Control 0.001
 
-PERL5LIB=/opt/disbatch; export PERL5LIB
-
-exec="/opt/disbatch/disbatchd.pl"
-prog="disbatchd"
-logfile="/var/log/disbatchd.log"
-
-lockfile="/var/lock/subsys/disbatchd"
-
-start() {
-    [ -x $exec ] || exit 5
-    echo -n $"Starting $prog: "
-    daemon "nohup $exec --quiet > $logfile 2>&1 &"
-    retval=$?
-    echo
-    [ $retval -eq 0 ] && touch $lockfile
-    return $retval
-}
-
-stop() {
-    echo -n $"Stopping $prog: "
-    killproc $prog
-    retval=$?
-    echo
-    [ $retval -eq 0 ] && rm -f $lockfile
-    return $retval
-}
-
-restart() {
-    stop
-    start
-}
-
-reload() {
-    restart
-}
-
-force_reload() {
-    restart
-}
-
-rh_status() {
-    # run checks to determine if the service is running or use generic status
-    status $prog
-}
-
-rh_status_q() {
-    rh_status >/dev/null 2>&1
-}
+### BEGIN INIT INFO
+# Provides:          disbatchd
+# Required-Start:    $syslog $remote_fs
+# Required-Stop:     $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: disbatchd
+# Description:       Daemon for disbatchd.pl
+### END INIT INFO`
 
 
-case "$1" in
-    start)
-        $1
-        ;;
-    stop)
-        $1
-        ;;
-    restart)
-        $1
-        ;;
-    reload)
-        $1
-        ;;
-    force-reload)
-        force_reload
-        ;;
-    status)
-        rh_status
-        ;;
-    condrestart|try-restart)
-        restart
-        ;;
-    *)
-        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
-        exit 2
-esac
-exit $?
+
+
+
+if [ -x /etc/disbatch/disbatchd-init ];
+then
+    /etc/disbatch/disbatchd-init $1
+else
+    echo "Required program /etc/disbatch/disbatchd-init not found!"
+    exit 1;
+fi
